### ISSUE TITLE
关于StrongWeakDance的文章应该搞错了

### ISSUE THREAD

**Issue by lilidan** [bestswifter/blog#1]
https://github.com/bestswifter/blog/blob/master/articles/objc-strong-weak-dance.md

看其他人写的文章，Strong Weak dance并不能解决这个问题,只能做一个判空

http://kuailejim.com/2017/01/05/Weak-Strong-Dance%E7%9C%9F%E7%9A%84%E5%AE%89%E5%85%A8%E5%90%97%EF%BC%9F/
https://www.jianshu.com/p/4e6153ea2734

**Comment by bestswifter** [comment]
我读过 kuailejim 的文章也和他交流过，他并不认为我说的有问题

可以明确的是，如果 block 执行前 self 就被释放，显然 block 也被释放掉了，这与 StrongWeakDance 无关。

我认为 StrongWeakDance 解决的是当 block 在执行时，另一个线程里 self 被释放的问题。

**Comment by bestswifter** [comment]
看起来并没有什么分歧，先 close 了
