### ISSUE TITLE
QUIC的文章中head-of-line blocking的简写错了

### ISSUE THREAD

**Issue by damon8to24** [bestswifter/blog#2]
队头阻塞（Head-of-line blocking或缩写为HOL blocking）在计算机网络的范畴中是一种性能受限的现象。它的原因是一列的第一个数据包（队头）受阻而导致整列数据包受阻。例如它有可能在缓存式输入的交换机中出现，有可能因为传输顺序错乱而出现，亦有可能在HTTP流水线中有多个请求的情况下出现。

摘自
https://zh.wikipedia.org/wiki/%E9%98%9F%E5%A4%B4%E9%98%BB%E5%A1%9E

**Comment by bestswifter** [comment]
感谢指正，已经改过来了
